version: 0.2

phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://www.oncloudconsulting/